version: 2.1
orbs:
    sonarcloud: sonarsource/sonarcloud@3.0.1
commands:
    setup-artifacts:
        steps:
            - run: mkdir ./coverage && mkdir ./coverage/lint && mkdir ./coverage/reports || exit 0
    python-install:
        steps:
            - run: pip install pipenv
            - run: pipenv install
    pipenv-install-dev:
        steps:
            - restore_cache:
                key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - run: pip install pipenv
            - run: pipenv install --dev
            - save_cache:
                key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
                paths:
                    - ".venv"
    pypi-setup:
        steps:
            - run: echo -e "[pypi]" >> ~/.pypirc
            - run: echo -e "username = __token__" >> ~/.pypirc
            - run: echo -e "password = $PYPI_TOKEN" >> ~/.pypirc
    pypi-deploy:
        steps:
            - run: python3 -m pip install --user --upgrade setuptools wheel
            - run: python3 setup.py sdist bdist_wheel
            - run: python3 -m pip install --user --upgrade twine
            - run: python3 -m twine upload dist/*
jobs:
    install:
        docker:
            - image: cimg/python:3.9
        steps:
            - checkout:
                method: full
            - pipenv-install-dev
            - persist_to_workspace:
                root: .
                paths:
                    - .venv
    lint:
        docker:
            - image: cimg/python:3.9
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run: pip install pipenv
            - setup-artifacts
            - run: python3 -m pipenv run lint | python3 -m pipenv run pylint_report.py > ./coverage/lint/report.html || exit 0
            - store_artifacts:
                path: ./coverage/lint/report.html
    test:
        docker:
            - image: cimg/python:3.9
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run: pip install pipenv
            - setup-artifacts
            - run: pipenv run test
            - run: pipenv run coverage
            - persist_to_workspace:
                root: .
                paths:
                    - coverage
            - store_test_results:
                path: ./coverage
            - store_artifacts:
                path: ./coverage
    sonarcloud-scan:
        docker:
            - image: cimg/python:3.9
        steps:
            - checkout
            - attach_workspace:
                at: .
            - sonarcloud/scan
    install-build-deploy:
        docker:
            - image: cimg/python:3.9
        steps:
            - checkout
            - python-install
            - pypi-setup
            - pypi-deploy
workflows:
    install-build-deploy-workflow:
        jobs:
            - install-build-deploy:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
    install-build-test-workflow:
        jobs:
            - install:
                filters:
                    tags:
                        ignore: /.*/
            - lint:
                requires:
                    - install
                filters:
                    tags:
                        ignore: /.*/
            - test:
                requires:
                    - install
                filters:
                    tags:
                        ignore: /.*/
            - sonarcloud-scan:
                context:
                    - sonarcloud
                requires:
                    - test
                filters:
                    tags:
                        ignore: /.*/
