version: 2.1
orbs:
    sonarcloud: sonarsource/sonarcloud@3.0.1
commands:
    setup-artifacts:
        steps:
            - run: mkdir ./coverage && mkdir ./coverage/lint && mkdir ./coverage/reports || exit 0
    uv-install-dev:
        steps:
            - restore_cache:
                key: uv-v1-{{ .Branch }}-{{ checksum "uv.lock" }}
            - run: pip install --upgrade uv
            - run: uv sync --frozen
            - save_cache:
                key: uv-v1-{{ .Branch }}-{{ checksum "uv.lock" }}
                paths:
                    - ".venv"
                    - "~/.cache/uv"
    pypi-setup:
        steps:
            - run: echo -e "[pypi]" >> ~/.pypirc
            - run: echo -e "username = __token__" >> ~/.pypirc
            - run: echo -e "password = $PYPI_TOKEN" >> ~/.pypirc
    pypi-deploy:
        steps:
            - run: pip install --upgrade uv twine
            - run: uv version "$CIRCLE_TAG"
            - run: uv build
            - run: python3 -m twine upload dist/*
jobs:
    install:
        docker:
            - image: cimg/python:3.9
        steps:
            - checkout:
                method: full
            - uv-install-dev
            - persist_to_workspace:
                root: .
                paths:
                    - .venv
    lint:
        docker:
            - image: cimg/python:3.9
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run: pip install --upgrade uv
            - setup-artifacts
            - run: uv run task lint | uv run pylint_report.py > ./coverage/lint/report.html || exit 0
            - store_artifacts:
                path: ./coverage/lint/report.html
    test:
        docker:
            - image: cimg/python:3.9
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run: pip install --upgrade uv
            - setup-artifacts
            - run: uv run task test
            - run: uv run task coverage
            - persist_to_workspace:
                root: .
                paths:
                    - coverage
            - store_test_results:
                path: ./coverage
            - store_artifacts:
                path: ./coverage
    sonarcloud-scan:
        docker:
            - image: cimg/python:3.9
        steps:
            - checkout:
                method: full
            - attach_workspace:
                at: .
            - sonarcloud/scan
    install-build-deploy:
        docker:
            - image: cimg/python:3.9
        steps:
            - checkout
            - pypi-setup
            - pypi-deploy
workflows:
    install-build-deploy-workflow:
        jobs:
            - install-build-deploy:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
    install-build-test-workflow:
        jobs:
            - install:
                filters:
                    tags:
                        ignore: /.*/
            - lint:
                requires:
                    - install
                filters:
                    tags:
                        ignore: /.*/
            - test:
                requires:
                    - install
                filters:
                    tags:
                        ignore: /.*/
            - sonarcloud-scan:
                context:
                    - sonarcloud
                requires:
                    - test
                filters:
                    tags:
                        ignore: /.*/
